-- 宝宝相册功能
-- albums 表
CREATE TABLE IF NOT EXISTS albums (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL COMMENT '相册标题',
  description VARCHAR(500) DEFAULT '' COMMENT '相册描述',
  cover_image VARCHAR(500) DEFAULT '' COMMENT '封面图路径',
  baby_name VARCHAR(50) DEFAULT '' COMMENT '宝宝昵称',
  baby_birth_date DATE DEFAULT NULL COMMENT '宝宝出生日期',
  author_id BIGINT NOT NULL COMMENT '创建者ID',
  photo_count INT DEFAULT 0 COMMENT '照片数量',
  is_private TINYINT(1) DEFAULT 1 COMMENT '是否私密',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_author (author_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- photos 表
CREATE TABLE IF NOT EXISTS photos (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  album_id BIGINT NOT NULL COMMENT '所属相册ID',
  path VARCHAR(500) NOT NULL COMMENT '图片路径',
  filename VARCHAR(255) NOT NULL COMMENT '原始文件名',
  size BIGINT DEFAULT 0 COMMENT '文件大小',
  title VARCHAR(200) DEFAULT '' COMMENT '照片标题',
  description VARCHAR(500) DEFAULT '' COMMENT '照片描述',
  taken_at DATETIME DEFAULT NULL COMMENT '拍摄时间',
  sort_order INT DEFAULT 0 COMMENT '排序序号',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_album (album_id),
  INDEX idx_taken (taken_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
